### ISSUE TITLE
[To-Do] Documentation

### ISSUE THREAD

**Issue by notronaldmcdonald** [notronaldmcdonald/fpm#53]
### Main point

Write documentation for using and modding the package manager.

### Tasklist

- [x] Update [README.md](fpm/core/README.md) with a 'usage' section.
- [x] Create `INSTALL.md` in `fpm/core`.
- [x] Create `README.md` in `fpm/core/constructor`.
- [x] Create a `devel.md` file in `fpm/core/src` to explain the code structure and how to modify it.

**Comment by notronaldmcdonald** [comment]
finished all docs - close with merge
