### ISSUE TITLE
[To-Do] Code cleanup + Better user experience

### ISSUE THREAD

**Issue by notronaldmcdonald** [notronaldmcdonald/fpm#72]
### Main points

* The code has some unused elements. These should be removed.
* Some of the commands that shouldn't need an argument require a third argument.
     * Solve this by moving the code that only needs two arguments to the top of the script.
* *Maybe* add some better comments throughout the scripts/code.

### Checklist

- [x] Remove any unused code.
- [x] Move two-argument commands above the syntax error message.
- [x] Possibly add comments.

**Comment by notronaldmcdonald** [comment]
partially added comments - mostly to variables

**Comment by notronaldmcdonald** [comment]
everything confirmed to work, closing.
