### ISSUE TITLE
[To-Do] Add help browser

### ISSUE THREAD

**Issue by notronaldmcdonald** [notronaldmcdonald/fpm#73]
### Main point

* Add a way for users to view package help documentation.
* Place above the syntax error message to avoid clunky use. (related to issue #72)
* Give it Windows support. (issue #45)

### Checklist

- [x] Create a help documentation browser.
- [ ] Give it Windows support.
- [x] Add help documentation as a recommendation to the packaging standard.
- [x] Keep it above the syntax error message.

**Comment by notronaldmcdonald** [comment]
all good outside of windows support.
