### ISSUE TITLE
[To-Do] 2.2.0 - General

### ISSUE THREAD

**Issue by notronaldmcdonald** [notronaldmcdonald/fpm#81]
Release v2.2.0

- [x] Complete all related issues
- [x] Remove unnecessary code
- [x] Adjust documentation as needed
