### ISSUE TITLE
[To-Do] 2.2.0 - Package format redesign

### ISSUE THREAD

**Issue by notronaldmcdonald** [notronaldmcdonald/fpm#84]
# Main point
- Packages remain as .tar.gz files
- Use a new index system (every package submits an index file)
- Update constructor to build the new packages
# Checklist
- [x] New package folder structure
- [x] Write index files format
- [x] Update package manager code to handle new package format
- [x] Packages keep their hashes in said index file (issue #83)
- [ ] Update constructor

**Comment by notronaldmcdonald** [comment]
using an arch build system-inspired method; constructor generates a basic ruby script with an install function to handle the installation as opposed to writing checks in `install_spine`

**Comment by notronaldmcdonald** [comment]
drop constructor
